import type { Slide } from "../types";

export const idorSlides: Slide[] = [
  {
    kicker: "Scenario 01 · Panoramica",
    title: "Vulnerabilità IDOR",
    body: "IDOR sta per Insecure Direct Object Reference: quando l'app espone pubblicamente l'id di una risorsa (un numero, un codice) e si dimentica di chiedersi «chi lo sta usando ha davvero il diritto di vederlo?».",
    note: "È una delle vulnerabilità più diffuse al mondo, e anche una delle più facili da capire: nessun attacco esotico, solo un numero cambiato nella URL.",
    bullets: ["Nessuno strumento richiesto", "Una URL manipolabile basta", "Lo troverai in quasi ogni app web"],
    accent: "gold",
    icon: "ShieldAlert",
  },
  {
    kicker: "Task 01 · Osserva",
    title: "Ogni cosa ha un id",
    body: "Ordini, fatture, profili, file: dentro un'app tutto è identificato da un numero o un codice. Il primo passo è allenare l'occhio a individuarli — nella barra degli URL, nei form, nelle chiamate API che la pagina fa per te.",
    note: "Nessun attacco qui: guardiamo solo dove l'app espone i suoi oggetti. Individuare l'id è sempre il primo passo prima di qualsiasi test.",
    bullets: [
      "Dove cercare: URL, query, cookie, body JSON",
      "Esempio: /ordini/1042 → l'id è 1042",
      "Annota tutto: ti servirà nei task successivi",
    ],
    icon: "Eye",
  },
  {
    kicker: "Task 02 · Il primo IDOR",
    title: "Cambia l'id, leggi l'ordine di un altro",
    body: "Sei loggato come cliente e la tua pagina mostra l'ordine 1042. Modifichi 1042 in 1043 nella barra dell'URL: se il server non controlla chi è il proprietario, ti mostra un ordine che non è tuo.",
    note: "Il difetto è doppio: l'app si fida del numero che arriva dal browser, e il server non chiede «questo ordine appartiene davvero all'utente che lo sta chiedendo?».",
    accent: "danger",
    icon: "MousePointerClick",
  },
  {
    kicker: "Task 03 · Enumeration",
    title: "Da un id a mille",
    body: "Un attaccante non prova un solo numero: itera migliaia di id con uno script (id fuzzing) e in pochi minuti scarica intere basi dati. Nel task proverai a passare in rassegna una serie di ordini uno dopo l'altro.",
    note: "Gli id sequenziali (1042, 1043, 1044…) sono il target ideale: ogni numero esiste, e ogni numero è un ordine di qualcuno. Rischio GDPR reale: dati personali esposti in massa.",
    bullets: [
      "Id sequenziali = enumeration facile",
      "Fatture, contratti, buste paga: tutto scaricabile",
      "Conseguenza legale, non solo tecnica",
    ],
    accent: "danger",
    icon: "Layers",
  },
  {
    kicker: "Task 04 · Privilege escalation",
    title: "id = 1 è quasi sempre l'admin",
    body: "In quasi ogni applicazione il primo utente creato è l'amministratore, e se gli id partono da 1, provare /profile/1 significa tentare di aprire il pannello di controllo di sistema senza credenziali.",
    note: "IDOR + id prevedibili = scalata dei privilegi: da cliente normale ad admin senza password. Nel task caricherai un profilo «sbagliato» e vedrai cosa si nasconde dietro.",
    accent: "danger",
    icon: "Crown",
  },
  {
    kicker: "Task 05-06 · Dove si nasconde",
    title: "Non solo URL: form e body",
    body: "Un IDOR può stare in un campo hidden di un form, in un JSON inviato con POST, in un header HTTP. La regola è una sola: tutto ciò che parte dal browser è manipolabile con DevTools o Burp in pochi secondi.",
    note: "Il browser mostra all'utente solo la parte visibile, ma i dati manipolabili sono tutti quelli in transito: ogni campo nascosto, ogni header, ogni cookie.",
    bullets: [
      "/download?doc=87 → cambia il numero e scarichi il documento di un altro",
      "userId hidden nei form: apri DevTools e vedrai il campo",
      "«Never trust the client»: il client è sempre in mano a un attaccante",
    ],
    icon: "Boxes",
  },
  {
    kicker: "Task 07 · UUID",
    title: "Anche gli id lunghi possono ingannare",
    body: "Un UUID sembra una difesa perfetta: 32 caratteri esadecimali, trilioni di combinazioni. Ma non è magico: se generato male (contatori, timestamp, RNG debole) resta indovinabile, e la lunghezza dà solo un falso senso di sicurezza.",
    note: "La difesa vera è la casualità crittografica: crypto.randomUUID() nel browser, gen_random_uuid() in PostgreSQL. E comunque resta una difesa in profondità: non sostituisce il controllo di autorizzazione lato server.",
    bullets: [
      "crypto.randomUUID(): generazione sicura",
      "gen_random_uuid() in PostgreSQL",
      "Difesa in profondità, mai un sostituto",
    ],
    icon: "Fingerprint",
  },
  {
    kicker: "Task 08 · API REST",
    title: "Stesso attacco, contesto più veloce",
    body: "Le API espongono le risorse in modo diretto: GET /api/users/42 restituisce il profilo 42 come JSON. Non c'è UI a mediare, non c'è rallentamento: la stessa manipolazione dell'id è ancora più immediata.",
    note: "Il pattern di attacco non cambia affatto — si cambia solo il numero — ma l'impatto è amplificato: le API sono fatte per essere chiamate in serie, esattamente ciò che serve all'enumeration.",
    accent: "danger",
    icon: "Network",
  },
  {
    kicker: "Task 09 · Client bypass",
    title: "Il browser non è una difesa",
    body: "Un bottone «disabled» blocca solo il click nel tuo browser. Con DevTools lo togli in due secondi e l'azione parte lo stesso, se il server non ricontrolla. Nel task fisserai questo principio in pratica.",
    note: "Nascondere all'utente normale non equivale a difendersi: un attaccante vede tutto ciò che l'app invia e può eseguire qualunque azione esista nel protocollo, non solo quelle esposte dall'interfaccia.",
    icon: "Unlock",
  },
  {
    kicker: "Task 10 · Sintesi",
    title: "Le tre regole d'oro",
    body: "Dieci domande finali per fissare i concetti, poi si passa alla pratica. Se le rispondi tutte, hai capito l'IDOR: ricapitola con le tre regole che vorresti vedere in ogni applicazione che usi.",
    note: "Consiglio: rispondi prima senza rileggere le slide. Le domande non sono difficili, servono solo a capire se i concetti sono entrati.",
    bullets: [
      "1 · Autorizzazione sempre lato server, per ogni richiesta",
      "2 · Id non prevedibili (UUID casuali, chiavi opache)",
      "3 · Mai fidarsi del client: form, header, JS, tutto è manipolabile",
    ],
    accent: "success",
    icon: "ShieldCheck",
  },
];
