import type { Scenario } from "../types";
import Task01Scope from "./tasks/Task01Scope";
import Task02PassiveActive from "./tasks/Task02PassiveActive";
import Task03Dns from "./tasks/Task03Dns";
import Task04Whois from "./tasks/Task04Whois";
import Task05Certificates from "./tasks/Task05Certificates";
import Task06Fingerprint from "./tasks/Task06Fingerprint";
import Task07Search from "./tasks/Task07Search";
import Task08Metadata from "./tasks/Task08Metadata";
import Task09EvidenceMap from "./tasks/Task09EvidenceMap";
import Task10Briefing from "./tasks/Task10Briefing";

export const informationGatheringScenario: Scenario = {
 id:"information-gathering",slug:"information-gathering",title:"Information Gathering",subtitle:"Raccogliere, verificare e organizzare informazioni prima di un pentest autorizzato",
 intro:"Ogni pentest efficace comincia prima delle scansioni: bisogna capire il perimetro, osservare le fonti pubbliche e distinguere i fatti dalle ipotesi. In questo scenario costruirai una piccola indagine su un'organizzazione immaginaria. Esplorerai DNS, WHOIS, certificati, tecnologie web, ricerche mirate e metadati, sempre con dati simulati e senza contattare sistemi reali. Il risultato non sarà una lista disordinata di nomi, ma un briefing chiaro che indica fonti, livello di confidenza e prossimi passi autorizzati.",
 highlights:["Perimetro, raccolta passiva e differenza rispetto alle verifiche attive.","DNS, WHOIS, certificati TLS, impronta web, ricerche e metadati.","Mappa delle evidenze e briefing finale con priorità e livello di confidenza."],
 category:"Metodologia Pentest",difficulty:"Base",status:"available",
 tasks:[
  {id:"01-perimetro",title:"Definisci il perimetro",goal:"Creare una scheda di ingaggio chiara prima della raccolta",brief:"L'information gathering non comincia da uno strumento, ma dall'autorizzazione. Il perimetro stabilisce quali asset puoi osservare, in quali orari e chi contattare se emerge un problema.",details: `Un dominio simile a quello del cliente non è automaticamente incluso. Anche una fonte pubblica va usata nel rispetto dello scopo concordato, perché i dati raccolti possono riguardare persone o sistemi esterni.

Una buona scheda separa ciò che è incluso da ciò che è escluso e conserva un contatto operativo. Comporrai la scheda del progetto Aurora scegliendo soltanto gli elementi necessari.`,hint:"Includi dominio, orari e referente. Le caselle personali sono esplicitamente escluse.",explanation:"Hai stabilito il confine legale e operativo dell'indagine.",Simulation:Task01Scope},
  {id:"02-passivo-attivo",title:"Passivo o attivo?",goal:"Distinguere osservazione pubblica e contatto diretto",brief:"La raccolta passiva consulta informazioni già disponibili presso fonti terze. Quella attiva invia invece una richiesta verso l'infrastruttura osservata, lasciando potenzialmente una traccia.",details: `La differenza non indica che un metodo sia sempre buono e l'altro cattivo. Indica soprattutto rischio e visibilità. Un test può includerli entrambi, ma le azioni attive richiedono limiti più precisi.

Attraverserai cinque bivi. Per ciascuna tecnica dovrai riconoscere se stai semplicemente leggendo una fonte o contattando direttamente il bersaglio.`,hint:"Domandati dove arriva la richiesta: a una fonte già pubblica o al sistema dell'organizzazione?",explanation:"Hai distinto due modalità di raccolta con impatti differenti.",Simulation:Task02PassiveActive},
  {id:"03-dns",title:"Anatomia di un dominio",goal:"Leggere i record DNS principali come una mappa",brief:"Il DNS traduce nomi leggibili in informazioni operative. I record possono indicare indirizzi, server di posta, autorità del dominio e policy testuali.",details: `Un record isolato racconta poco; insieme, A, MX, NS e TXT descrivono una parte dell'esposizione pubblica. Questa mappa aiuta a preparare domande migliori per le fasi successive.

Aprirai quattro rami del dominio simulato. Osserva il tipo, il valore e soprattutto la funzione, senza dedurre **vulnerabilità** dalla sola presenza di un servizio.`,hint:"A punta a un indirizzo; MX parla di posta; NS di autorità DNS; TXT contiene testo strutturato.",explanation:"Sai interpretare i record DNS fondamentali senza attribuire loro significati eccessivi.",Simulation:Task03Dns},
  {id:"04-whois",title:"WHOIS sotto la lente",goal:"Estrarre informazioni amministrative da una scheda di dominio",brief:"WHOIS e i servizi di registrazione mostrano dati sul ciclo di vita di un dominio. Molti contatti sono protetti per privacy, mentre registrar, date e nameserver restano spesso visibili.",details: `La protezione del registrante è normale e non è un segnale sospetto. Le date possono suggerire se un dominio è recente; i nameserver aiutano a capire chi gestisce il **DNS**, ma nessuno di questi campi dimostra da solo la proprietà tecnica di altri asset.

Metterai a fuoco quattro aree di una scheda simulata e annoterai il significato corretto di ciascuna.`,hint:"Cerca chi gestisce la registrazione, le date, i server DNS e la presenza della privacy.",explanation:"Hai letto una scheda WHOIS distinguendo fatti visibili e dati volutamente protetti.",Simulation:Task04Whois},
  {id:"05-certificati",title:"Certificati e sottodomini",goal:"Usare i nomi di un certificato per ampliare l'inventario",brief:"I certificati TLS possono contenere più nomi validi per lo stesso progetto. I registri di trasparenza rendono pubbliche molte emissioni e possono rivelare servizi non collegati dalla home page.",details: `Un nome come api o status suggerisce una funzione, ma non garantisce che il servizio sia ancora attivo. L'inventory deve quindi conservare la fonte e prevedere una verifica successiva autorizzata.

Farai emergere una piccola costellazione da un certificato simulato. Ogni stella sarà una pista, non una **vulnerabilità**.`,hint:"Continua a interrogare il certificato finché tutti i nomi associati sono visibili.",explanation:"Hai trasformato un certificato pubblico in un elenco di possibili asset da verificare.",Simulation:Task05Certificates},
  {id:"06-impronta",title:"Impronta tecnologica",goal:"Combinare indizi web senza scambiarli per certezze",brief:"Una pagina pubblica può lasciare indizi nelle intestazioni, nel codice e nei cookie. Il fingerprinting organizza questi segnali per ipotizzare quali tecnologie sostengono il servizio.",details: `Le intestazioni possono essere cambiate, un frammento JavaScript può rimanere da una versione precedente e un proxy può nascondere il server reale. Per questo una buona nota usa parole come “possibile” e indica sempre la fonte.

Aprirai tre strati della pagina di Aurora e costruirai un'impronta prudente, basata sulla convergenza degli indizi.`,hint:"Esamina tutti gli strati; nessuno, da solo, è una prova definitiva.",explanation:"Hai composto un fingerprint documentato e con il giusto livello di confidenza.",Simulation:Task06Fingerprint},
  {id:"07-ricerca",title:"Motore di ricerca consapevole",goal:"Costruire una query precisa e proporzionata",brief:"Gli operatori di ricerca aiutano a ridurre il rumore: si può limitare una query a un dominio, a un formato di file e a un argomento pertinente al test.",details: `Essere in grado di cercare un dato non significa doverlo cercare. La raccolta deve restare necessaria e proporzionata all'obiettivo. Documenti pubblici possono rivelare nomi, processi e tecnologie senza ricorrere a ricerche invasive.

Assemblerai una query a blocchi per trovare un rapporto pubblico in PDF, evitando parole orientate alla ricerca di credenziali.`,hint:"Combina dominio, formato PDF e argomento report.",explanation:"Hai creato una ricerca OSINT mirata, utile e coerente con lo scopo.",Simulation:Task07Search},
  {id:"08-metadati",title:"Metadati dei documenti",goal:"Valutare le informazioni nascoste in un file pubblico",brief:"I metadati descrivono come un documento è stato creato: autore, software, date, percorso originale o coordinate. Possono offrire contesto, ma anche esporre dettagli interni.",details: `Un nome autore può suggerire una convenzione, mentre una versione software non dimostra automaticamente una **vulnerabilità**. Un percorso locale può contenere username o nomi di clienti e deve essere trattato con cautela nel rapporto.

Aprirai i cassetti di una scrivania digitale e valuterai ogni dato secondo utilità, sensibilità e forza dell'evidenza.`,hint:"Ispeziona tutti i cassetti: anche l'assenza di un dato va registrata senza inventare conclusioni.",explanation:"Hai classificato metadati utili, normali e sensibili con la necessaria prudenza.",Simulation:Task08Metadata},
  {id:"09-mappa",title:"Dagli indizi alla mappa",goal:"Collegare asset, fonti e livelli di confidenza",brief:"La raccolta produce frammenti. Una mappa delle evidenze li collega mostrando da dove proviene ogni relazione e quanto è affidabile.",details: `Un record **DNS** offre una relazione forte tra dominio e server di posta. Un annuncio di lavoro che cita il cloud è più debole: descrive competenze richieste, non necessariamente l'intera architettura.

Collegherai tre coppie sulla lavagna e sceglierai una formulazione che non trasformi una possibilità in certezza.`,hint:"Collega tutti gli indizi e usa una frase prudente per l'informazione proveniente dall'annuncio.",explanation:"Hai prodotto una mappa leggibile che separa prove solide e ipotesi.",Simulation:Task09EvidenceMap},
  {id:"10-briefing",title:"Briefing finale",goal:"Consegnare un dossier utile per la fase successiva",brief:"Il risultato dell'information gathering deve aiutare il team a decidere. Un buon briefing ricorda il perimetro, cita le fonti, assegna priorità e propone verifiche controllate.",details: `Un elenco di host senza contesto crea confusione. Al contrario, una conclusione troppo sicura può spingere il team fuori perimetro. Il dossier deve essere breve, verificabile e orientato a passi concordati.

Completerai quattro pagine scegliendo perimetro, qualità delle evidenze, priorità e prossimo passo. La consegna chiuderà il primo scenario della metodologia di pentesting.`,hint:"Scegli sempre l'opzione autorizzata, documentata e prudente.",explanation:"Hai completato l'Information Gathering con un briefing sicuro, chiaro e verificabile.",Simulation:Task10Briefing},
 ]
};