import type { Scenario } from "../types";
import Task01Updates from "./tasks/Task01Updates";
import Task02Privileges from "./tasks/Task02Privileges";
import Task03Permissions from "./tasks/Task03Permissions";
import Task04Services from "./tasks/Task04Services";
import Task05Firewall from "./tasks/Task05Firewall";
import Task06Ssh from "./tasks/Task06Ssh";
import Task07AuthLogs from "./tasks/Task07AuthLogs";
import Task08Processes from "./tasks/Task08Processes";
import Task09Audit from "./tasks/Task09Audit";
import Task10Quiz from "./tasks/Task10Quiz";

export const linuxSecurityScenario: Scenario = {
 id:"linux-security", slug:"linux-security", title:"Sicurezza dei sistemi Linux", subtitle:"Proteggere un server passo dopo passo, dalle patch al controllo dei log", intro:"Un sistema Linux non diventa sicuro grazie a un singolo comando. La protezione nasce da tante scelte semplici e coerenti: installare gli aggiornamenti, limitare i privilegi, lasciare attivi solo i servizi necessari e osservare ciò che succede. In questo scenario lavorerai su un server simulato e imparerai una routine di base pensata per chi parte da zero.", highlights:["Aggiornamenti, utenti e permessi secondo il minimo privilegio.","Servizi, firewall UFW e configurazione essenziale di SSH.","Lettura dei log, processi sospetti e controllo guidato del server."], category:"Difesa & Sistemi", difficulty:"Base", status:"available",
 tasks:[
  {id:"01-aggiornamenti",title:"Aggiornamenti e patch",goal:"Scegliere una routine di aggiornamento sicura",brief:"Le vulnerabilità scoperte nei programmi vengono spesso corrette con nuovi pacchetti. Un sistema che rimane indietro conserva difetti già conosciuti e documentati, quindi può diventare un bersaglio più facile anche per attacchi poco sofisticati.",details:"Aggiornare non significa premere un pulsante senza pensare. Prima si usano repository affidabili, poi si leggono gli aggiornamenti disponibili e, sui sistemi importanti, si pianifica il momento dell'installazione. Alcuni aggiornamenti richiedono il riavvio di un servizio o dell'intera macchina.\n\nLe **patch** di sicurezza sono particolarmente importanti perché riducono il tempo durante il quale una **vulnerabilità** nota può essere sfruttata. Un backup e una breve verifica dopo l'installazione completano una buona procedura.\n\nNell'attività valuterai quattro situazioni quotidiane e sceglierai la risposta più prudente per ciascuna.",hint:"Cerca sempre l'equilibrio tra rapidità della correzione, fonte affidabile e continuità del servizio.",explanation:"Sai impostare una routine di patching semplice: controllare la fonte, applicare gli aggiornamenti e completare i riavvii necessari.",Simulation:Task01Updates},
  {id:"02-privilegi",title:"Utenti, root e sudo",goal:"Usare il minimo privilegio necessario",brief:"Linux separa le attività normali da quelle amministrative. L'utente root può modificare quasi tutto il sistema; proprio per questo non dovrebbe essere usato per leggere la posta, navigare o svolgere operazioni quotidiane.",details:"Il principio del minimo privilegio dice che ogni persona e ogni programma devono ricevere soltanto i permessi utili al loro compito. Il **comando** **sudo** permette a un utente autorizzato di elevare i privilegi per una singola operazione, lasciando inoltre una traccia nei log.\n\nLimitare l'uso di **root** riduce la gravità di un errore: un **comando** sbagliato o un programma dannoso eseguito come utente normale incontra più ostacoli. Non elimina ogni rischio, ma contiene i possibili danni.\n\nDovrai decidere quale livello di privilegio è adatto a quattro attività comuni.",hint:"Se l'azione riguarda soltanto i tuoi file, root quasi certamente non serve.",explanation:"Hai applicato il minimo privilegio distinguendo le azioni quotidiane dalle modifiche amministrative.",Simulation:Task02Privileges},
  {id:"03-permessi",title:"Permessi senza eccessi",goal:"Proteggere script, documenti e segreti",brief:"I permessi stabiliscono chi può leggere, modificare o eseguire un file. Impostare 777 per risolvere velocemente un errore rende il file accessibile a chiunque e può trasformare un piccolo problema operativo in un rischio serio.",details:"Le tre cifre rappresentano proprietario, gruppo e altri utenti. I valori derivano dalla somma di lettura 4, scrittura 2 ed esecuzione 1. Per esempio 600 concede lettura e scrittura soltanto al proprietario; 644 rende un documento leggibile dagli altri, ma modificabile solo dal proprietario.\n\nNon esiste un permesso perfetto per ogni file: dipende dal suo scopo. Una chiave o un file di credenziali deve restare privato, mentre un manuale pubblico può essere letto da tutti.\n\nAbbina tre file alla configurazione più adatta, evitando privilegi inutili.",hint:"Parti dalla domanda: chi deve davvero leggere, modificare o eseguire questo file?",explanation:"Hai protetto file con esigenze diverse senza ricorrere a permessi eccessivi.",Simulation:Task03Permissions},
  {id:"04-servizi",title:"Servizi e porte esposte",goal:"Lasciare attivo soltanto ciò che serve",brief:"Un servizio in ascolto aspetta connessioni su una porta di rete. SSH, un sito web e un server di stampa possono essere legittimi, ma ogni programma esposto deve essere mantenuto, aggiornato e controllato.",details:"Ridurre la superficie di attacco significa eliminare le funzioni che il server non usa. Se una macchina pubblica soltanto un sito e viene amministrata con **SSH**, vecchi servizi come Telnet o **FTP** non devono restare attivi per abitudine.\n\nUna porta aperta non dimostra una compromissione. È però un invito a verificare quale processo la usa, perché è necessario e se comunica in modo sicuro. La decisione dipende sempre dal ruolo della macchina.\n\nEsamina l'elenco simulato e scegli quali servizi mantenere o disattivare.",hint:"Conserva solo SSH e il servizio web richiesti dalla descrizione del server.",explanation:"Hai ridotto la superficie di attacco collegando ogni porta a una necessità concreta.",Simulation:Task04Services},
  {id:"05-firewall",title:"Firewall essenziale con UFW",goal:"Consentire soltanto SSH e HTTP",brief:"Il firewall controlla quali connessioni possono raggiungere il sistema. UFW offre comandi semplici per definire una regola predefinita e aggiungere poche eccezioni per i servizi realmente necessari.",details:"Una configurazione prudente parte da deny incoming: le nuove connessioni in ingresso vengono bloccate, salvo quelle consentite esplicitamente. Si aprono quindi le porte 22 per **SSH** e 80 per **HTTP**, perché sono i due servizi previsti nel laboratorio.\n\nL'ordine conta soprattutto quando lavori da remoto: prima di abilitare il firewall devi consentire **SSH**, altrimenti potresti perdere l'accesso al server. Dopo ogni modifica è utile leggere lo stato effettivo delle regole.\n\nCostruisci il piccolo insieme di comandi corretto senza aprire Telnet.",hint:"Regola predefinita, eccezioni necessarie, attivazione: segui questa sequenza.",explanation:"Hai creato una politica di ingresso chiusa per impostazione predefinita, con due sole eccezioni motivate.",Simulation:Task05Firewall},
  {id:"06-ssh",title:"Mettere in sicurezza SSH",goal:"Configurare un accesso remoto più robusto",brief:"SSH consente di amministrare Linux a distanza usando una connessione cifrata. Essendo spesso raggiungibile dalla rete, è anche uno dei servizi più provati da bot e attaccanti con password comuni.",details:"Le chiavi **SSH** sono preferibili alle password perché non possono essere indovinate con tentativi ripetuti nello stesso modo. Vietare l'accesso diretto come **root** obbliga inoltre a entrare con un utente identificabile e ad usare **sudo** soltanto quando serve.\n\nRidurre MaxAuthTries limita i tentativi per connessione. Queste impostazioni aiutano, ma bisogna sempre mantenere aggiornato il servizio e verificare la nuova configurazione prima di chiudere la sessione già aperta.\n\nCompleta quattro righe essenziali di sshd_config scegliendo valori sicuri.",hint:"Chiavi sì, password e login diretto di root no, pochi tentativi.",explanation:"Hai configurato un accesso SSH essenziale basato su chiavi e senza login diretto dell'amministratore.",Simulation:Task06Ssh},
  {id:"07-log",title:"Leggere i log di autenticazione",goal:"Riconoscere tentativi di accesso sospetti",brief:"I log raccontano chi ha provato ad accedere, quando, da quale indirizzo e con quale risultato. Non impediscono da soli un attacco, ma permettono di vedere comportamenti che altrimenti resterebbero invisibili.",details:"Un singolo errore di password può essere normale. Molti tentativi in pochi secondi dallo stesso indirizzo, soprattutto contro nomi come **root**, admin e test, assomigliano invece a un attacco **brute force** automatizzato.\n\nL'analisi richiede contesto: un accesso riuscito può essere legittimo oppure no, mentre un errore non è sempre ostile. Orari, frequenza, provenienza e account coinvolti aiutano a costruire un giudizio.\n\nSeleziona le righe che insieme formano la sequenza sospetta.",hint:"Confronta gli orari e cerca lo stesso IP che cambia rapidamente nome utente.",explanation:"Hai riconosciuto un pattern di tentativi automatici senza confonderlo con un semplice errore umano.",Simulation:Task07AuthLogs},
  {id:"08-processi",title:"Processi sospetti",goal:"Individuare un'anomalia usando più indizi",brief:"Un processo è un programma in esecuzione. Controllare utente, comando, percorso e consumo di risorse aiuta a capire se ciò che gira sulla macchina è coerente con il suo ruolo.",details:"Nomi come sshd o nginx sono attesi su un server con **SSH** e sito web, ma anche un nome familiare potrebbe essere copiato da un malware. Per questo non bisogna giudicare da un solo campo. Un eseguibile nascosto in /tmp, avviato dall'utente del sito e con consumo anomalo merita attenzione.\n\nIl primo passo non è cancellare subito il file: si raccolgono informazioni, si controllano connessioni e origine, poi si contiene il problema seguendo la procedura dell'organizzazione.\n\nConfronta quattro processi e seleziona quello con la combinazione di indizi più anomala.",hint:"Guarda insieme percorso, utente, CPU e destinazione indicata nel comando.",explanation:"Hai identificato un processo sospetto basandoti su più segnali, non soltanto sul suo nome.",Simulation:Task08Processes},
  {id:"09-controllo",title:"Controllo guidato del sistema",goal:"Eseguire quattro verifiche di base",brief:"La sicurezza richiede controlli ripetuti. Una breve routine può mostrare aggiornamenti mancanti, porte inattese, firewall disattivato o accessi recenti che devono essere verificati.",details:"Nessun **comando** offre da solo una risposta completa. apt list --upgradable mostra i pacchetti aggiornabili; ss -tulpn elenca porte e processi in ascolto; ufw status riassume il firewall; last mostra gli accessi recenti.\n\nQuesti risultati vanno confrontati con ciò che ti aspetti dalla macchina. Due porte aperte possono essere corrette su un server web e insolite su una postazione personale. Il valore nasce dal confronto tra stato osservato e ruolo previsto.\n\nUsa il **terminale** simulato per completare i quattro controlli e leggere il riepilogo.",hint:"Digita help nel terminale per vedere l'elenco dei comandi ammessi.",explanation:"Hai completato una piccola checklist riutilizzabile per osservare lo stato di sicurezza di un sistema Linux.",Simulation:Task09Audit},
  {id:"10-quiz",title:"Quiz finale — 10 domande",goal:"Consolidare le basi di sicurezza Linux",brief:"Il quiz riprende le decisioni affrontate nello scenario: patch, privilegi, permessi, servizi, firewall, SSH, log e processi. Le domande restano pratiche e non richiedono di ricordare dettagli avanzati.",details:"Leggi ogni situazione e cerca la scelta che riduce il rischio senza rendere inutilizzabile il sistema. La sicurezza di base non consiste nel bloccare tutto, ma nel consentire solo ciò che serve e rendere visibili le anomalie.\n\nPer completare il percorso servono almeno sette risposte corrette su dieci. Se sbagli, vedrai le risposte corrette e potrai riprovare senza perdere i task già completati.\n\nUsa i principi appresi più che la memoria: aggiornare, limitare, ridurre e controllare.",hint:"Minimo privilegio, servizi necessari, accessi protetti e osservazione regolare sono i quattro fili conduttori.",explanation:"Hai completato le basi della sicurezza dei sistemi Linux e possiedi una routine iniziale concreta.",Simulation:Task10Quiz},
 ]
};
