import { useState } from "react";
import { InteractiveTerminal, type TermResponse } from "@/components/lab/InteractiveTerminal";
import { InfoNote, SuccessNote } from "@/components/lab/Feedback";
import { cn } from "@/lib/utils";
import type { TaskContext } from "../../types";
const CHECKS=[
 {key:"updates",label:"Controlla aggiornamenti",command:"apt list --upgradable"},
 {key:"ports",label:"Controlla porte",command:"ss -tulpn"},
 {key:"firewall",label:"Controlla firewall",command:"sudo ufw status"},
 {key:"log",label:"Controlla ultimi accessi",command:"last -n 3"},
];
export default function Task09Audit({markComplete,isComplete}:TaskContext){const [done,setDone]=useState<string[]>([]);const record=(key:string)=>setDone((p)=>p.includes(key)?p:[...p,key]);const handle=(raw:string):TermResponse|TermResponse[]=>{const cmd=raw.trim().toLowerCase();if(cmd==="help"||cmd==="?")return CHECKS.map((c)=>({text:c.command,kind:"info" as const}));if(cmd==="apt list --upgradable"){record("updates");return [{text:"Listing... Done"},{text:"openssl/jammy-security 3.0.2 [upgradable]",kind:"info"}];}if(cmd==="ss -tulpn"){record("ports");return [{text:"tcp LISTEN 0 128 0.0.0.0:22 users:((sshd))"},{text:"tcp LISTEN 0 511 0.0.0.0:80 users:((nginx))"}];}if(cmd==="sudo ufw status"||cmd==="ufw status"){record("firewall");return [{text:"Status: active",kind:"info"},{text:"22/tcp ALLOW Anywhere"},{text:"80/tcp ALLOW Anywhere"}];}if(cmd==="last -n 3"){record("log");return [{text:"marco pts/0 192.168.1.24 Sat Sep 12 09:12"},{text:"reboot system boot Sat Sep 12 08:40"}];}return {text:"Comando non previsto nel laboratorio. Digita help per vedere i quattro controlli.",kind:"err"};};if(done.length===CHECKS.length&&!isComplete)markComplete();return <div className="grid gap-4 md:grid-cols-[1fr_250px]"><InteractiveTerminal title="controllo sicurezza" prompt="student@server:~$ " heightClass="min-h-[300px]" onCommand={handle}/><aside className="rounded-lg border border-border bg-surface p-4"><h3 className="mb-3 font-mono text-xs uppercase text-accent">Controlli essenziali</h3><ul className="space-y-3">{CHECKS.map((check)=><li key={check.key} className={cn("flex gap-2 text-sm",done.includes(check.key)?"text-foreground":"text-muted-foreground")}><span className={cn("mt-1.5 h-2 w-2 shrink-0 rounded-full",done.includes(check.key)?"bg-success":"bg-border")}/><span>{check.label}<code className="mt-1 block break-all text-[10px] text-muted-foreground">{check.command}</code></span></li>)}</ul></aside><div className="md:col-span-2">{isComplete?<SuccessNote>Hai concluso un controllo di base: patch, porte, firewall e accessi offrono quattro punti di vista diversi sullo stato del server.</SuccessNote>:<InfoNote>Digita help se non ricordi i comandi. Questo non è un controllo completo, ma una piccola routine utile da ripetere con regolarità.</InfoNote>}</div></div>}
