import type { Slide } from "../types";

export const reverseShellSlides: Slide[] = [
  {
    kicker: "Scenario 03 · Panoramica",
    title: "Reverse Shell su IIS",
    body: "Una reverse shell è un modo per «prendere il controllo» di un server: invece di entrare noi nel server, è il server che si collega al nostro computer e ci apre una finestra di comandi. In questo scenario vediamo come un semplice upload dimenticato su un server Windows IIS può portare fino a lì.",
    note: "È la catena d'attacco più classica del mondo Windows: upload permissivo + cartella eseguibile + PowerShell. Ogni passaggio è simulato nel browser — nessun vero server, nessun vero attacco — ma i comandi e gli errori sono quelli reali.",
    bullets: [
      "Un upload mal configurato è spesso la porta d'ingresso",
      "Il server si collega a te: ecco il «reverse» di reverse shell",
      "Da una finestra web a una shell di comandi sul server",
    ],
    accent: "gold",
    icon: "Server",
  },
  {
    kicker: "Task 01 · Ricognizione",
    title: "Prima di tutto: guarda con cosa hai a che fare",
    body: "Prima di attaccare bisogna sapere con cosa si ha a che fare. Con una scansione delle porte scopriamo che il target è un server Windows con web server IIS. Questo cambia tutto: i file sono .aspx, i comandi sono PowerShell, e i file di prova sono altri.",
    note: "Ricognizione evita rumore inutile: attaccare un servizio che non c'è significa perdere tempo e farsi notare nei log. Esempio: nmap -sV 10.10.24.17 → Microsoft-IIS/10.0, Windows Server 2019.",
    bullets: [
      "nmap -sV: scopre porte, servizi e versioni",
      "Microsoft-IIS/10.0 = web server Microsoft su Windows",
      "Da qui in poi: payload ASPX/PowerShell",
    ],
    icon: "ScanLine",
  },
  {
    kicker: "Task 02 · Mappa del sito",
    title: "Trovare dove si carica un file",
    body: "Un server IIS diventa pericoloso quando esistono tre cose insieme: un punto dove l'utente può caricare un file, una cartella dove quel file è raggiungibile via URL, e l'esecuzione degli script in quella stessa cartella. Nel task navighiamo il sito e leggiamo gli header HTTP per trovare il caricamento.",
    note: "Basta rompere uno dei tre lati del triangolo per neutralizzare tutto il vettore. Esempio: /upload accetta file, /uploads/ li serve pubblicamente.",
    bullets: [
      "Latte del triangolo: upload · serve · esegue",
      "Prova /upload e /uploads/",
      "Gli header HTTP rivelano spesso molto",
    ],
    icon: "Map",
  },
  {
    kicker: "Task 03 · Anatomia",
    title: "Com'è fatta una webshell ASPX",
    body: "Una webshell è una pagina eseguibile che accetta un comando dall'attaccante, lo passa al sistema operativo e restituisce l'output. In ASP.NET bastano poche righe: la direttiva di pagina, la lettura di ?cmd, la scrittura dell'output.",
    note: "In ASP.NET la sola presenza di <%@ Page Language=\"C#\" %> in un file .aspx è sufficiente perché IIS lo compili al volo ed esegua il codice: è il motivo per cui bastano poche righe per avere esecuzione arbitraria.",
    bullets: [
      "Direttiva di pagina + lettura ?cmd + output",
      "Poche righe di C# = canale di comando completo",
      "Punto di partenza: poi la sostituiremo con una reverse shell",
    ],
    accent: "danger",
    icon: "FileCode",
  },
  {
    kicker: "Task 04 · Webshell in azione",
    title: "Carica la webshell, esegui comandi",
    body: "Mettiamo in pratica: carichiamo cmd.aspx nell'endpoint di upload (oggi accetta qualunque estensione, inclusi gli .aspx), poi la apriamo nel browser e usiamo il form per eseguire whoami, ipconfig, dir. Ogni comando è una singola richiesta HTTP.",
    note: "L'output di whoami — iis apppool\\defaultapppool — rivela chi sei sul server: né Administrator né SYSTEM. Puoi già fare parecchio (leggere web.config, esplorare la webroot), ma il vero salto di qualità è ottenere una shell interattiva.",
    bullets: [
      "Comandi utili: whoami, hostname, ipconfig, dir",
      "L'endpoint accetta qualunque estensione: difetto elementare",
      "Ogni comando finisce nei log: attacco rumoroso ma efficace",
    ],
    accent: "danger",
    icon: "Terminal",
  },
  {
    kicker: "Task 05 · Listener",
    title: "Preparare la porta a cui il server si collegherà",
    body: "Una reverse shell funziona così: la vittima si connette a te. Ti serve quindi un listener che accetti la connessione in arrivo. netcat (nc) è l'attrezzo standard: -l = listen, -v = verbose, -n = no DNS, -p = port.",
    note: "Scegli con criterio la porta: sotto 1024 servono privilegi di root; le porte più «invisibili» sono quelle che il firewall aziendale della vittima probabilmente lascia aperte in uscita (443, 8443, 53). Nei CTF si usa spesso 4444 o 9001 per convenzione.",
    bullets: [
      "nc -lvnp <porta> = listener standard",
      "Porte più credibili: 443, 8443, 53",
      "Nei CTF: 4444 o 9001 per convenzione",
    ],
    icon: "Radio",
  },
  {
    kicker: "Task 06 · Payload",
    title: "Costruire shell.aspx con LHOST e LPORT",
    body: "Ora componiamo il payload: un file .aspx che, quando IIS lo esegue, avvia PowerShell con una one-liner che apre una connessione verso il tuo listener. Due parametri universali: LHOST è il tuo IP raggiungibile dalla vittima, LPORT la porta su cui stai ascoltando.",
    note: "La one-liner (la classica PowerShell reverse shell, originariamente di Nishang) crea un socket TCP verso LHOST:LPORT e collega input/output di powershell.exe al socket. Sbagliare LHOST o LPORT significa nessuna connessione — LPORT deve coincidere con la porta del listener.",
    bullets: [
      "LHOST = tuo IP · LPORT = porta del listener",
      "File .aspx + one-liner PowerShell = payload completo",
      "Sbagliare uno dei due parametri = nessuna shell",
    ],
    accent: "danger",
    icon: "Socket",
  },
  {
    kicker: "Task 07 · Il momento chiave",
    title: "Carica shell.aspx e trigga l'URL",
    body: "Carica shell.aspx nella cartella /uploads/, poi apri il suo URL dal browser. IIS lo compila, PowerShell parte, si connette al listener: shell aperta. È il momento in cui meccanicamente avviene un'intera compromissione.",
    note: "La sequenza esatta: POST /upload → IIS salva in /uploads/shell.aspx → apri l'URL → IIS esegue powershell.exe → powershell apre TCPClient(LHOST, LPORT) → il tuo nc mostra «connect from …» e ti trovi davanti al prompt PS della vittima.",
    bullets: [
      "Prima Carica, poi Trigger",
      "Guarda il terminale: la connessione entra da sola",
      "Difesa più economica: non far eseguire gli .aspx caricati",
    ],
    accent: "danger",
    icon: "Zap",
  },
  {
    kicker: "Task 08 · Post-exploitation",
    title: "Dentro il server: guardarsi intorno",
    body: "Ora hai un prompt PowerShell sul server. La post-exploitation è la fase in cui l'attaccante trasforma «esecuzione remota di comandi» in «controllo utile»: cerca credenziali, enumera utenti, scarica strumenti aggiuntivi, cerca vie di escalation.",
    note: "Il vero danno raramente sta nel web server in sé: sta nelle credenziali che quel web server conosce (DB, servizi cloud, altri sistemi). Ecco perché non tenere segreti in file leggibili dal processo web è una difesa più profonda di qualunque WAF.",
    bullets: [
      "Chi sei: whoami · hostname",
      "Cosa conosce il server: web.config, appsettings.json",
      "Vie di escalation da IIS APPPOOL a SYSTEM",
    ],
    icon: "Search",
  },
  {
    kicker: "Task 09-10 · Difese e sintesi",
    title: "Cosa funziona davvero: difese e quiz",
    body: "Il modo migliore per fissare i concetti è ragionare al contrario: dato l'attacco appena eseguito, quali controlli avrebbero rotto la catena? Nel task 9 selezioni le contromisure vere (escludendo quelle cosmetiche); nel task 10 il quiz finale di 10 domande consolida tutta la catena.",
    note: "Chiediti per ogni voce: «un attaccante con un terminale può aggirarla?». Le difese efficaci: prevenzione robusta all'upload, handler disabilitato in /uploads, app pool a bassi privilegi, egress filter. Se sbagli il quiz, torna al task corrispondente — non c'è penalità nel riprovare.",
    bullets: [
      "1 · Non far eseguire gli .aspx caricati (accessPolicy=\"Read\")",
      "2 · Application pool con privilegi minimi",
      "3 · Egress filtering: la vittima non deve potersi collegare fuori",
    ],
    accent: "success",
    icon: "ShieldCheck",
  },
];
