import type { Scenario } from "../types";
import Task01Updates from "./tasks/Task01Updates";
import Task02Accounts from "./tasks/Task02Accounts";
import Task03Uac from "./tasks/Task03Uac";
import Task04Defender from "./tasks/Task04Defender";
import Task05Firewall from "./tasks/Task05Firewall";
import Task06Permissions from "./tasks/Task06Permissions";
import Task07Startup from "./tasks/Task07Startup";
import Task08Events from "./tasks/Task08Events";
import Task09Audit from "./tasks/Task09Audit";
import Task10Quiz from "./tasks/Task10Quiz";

export const windowsSecurityScenario: Scenario = {
  id: "windows-security",
  slug: "windows-security",
  title: "Sicurezza dei Sistemi Windows",
  subtitle: "Proteggere un PC con aggiornamenti, privilegi, difese integrate e controlli regolari",
  intro: "La sicurezza di Windows non dipende da un singolo antivirus. Nasce da una serie di decisioni comprensibili: installare le correzioni, usare i privilegi con attenzione, mantenere attive le difese integrate e sapere dove cercare quando qualcosa sembra insolito. In questo scenario lavorerai su una postazione simulata e costruirai una routine adatta a chi parte da zero.",
  highlights: [
    "Windows Update, account standard e richieste UAC valutate con attenzione.",
    "Microsoft Defender, firewall e permessi delle cartelle senza eccessi.",
    "Programmi all'avvio, eventi di accesso e controllo guidato con PowerShell.",
  ],
  category: "Difesa & Sistemi",
  difficulty: "Base",
  status: "available",
  tasks: [
    { id: "01-aggiornamenti", title: "Aggiornamenti e Windows Update", goal: "Costruire una routine di aggiornamento affidabile", brief: "Le patch correggono difetti del sistema e delle applicazioni. Quando una vulnerabilità diventa pubblica, rimandare a lungo un aggiornamento significa lasciare aperto un problema che altri conoscono già.", details: "Windows Update raccoglie molte correzioni del sistema, delle protezioni e dei driver. Per altri programmi è meglio usare il loro aggiornamento integrato o il sito ufficiale del produttore, evitando strumenti sconosciuti che promettono di aggiornare tutto con un clic.\n\nAnche il riavvio fa parte dell'aggiornamento: alcuni file non possono essere sostituiti mentre sono in uso. Su un PC di lavoro si salva ciò che è aperto e si sceglie un momento vicino che non interrompa un'attività importante.\n\nValuterai tre situazioni realistiche, bilanciando sicurezza e continuità del lavoro.", hint: "Preferisci fonti ufficiali e un rinvio breve e pianificato, non indefinito.", explanation: "Sai gestire aggiornamenti e riavvii senza affidarti a fonti dubbie o lasciare il PC scoperto troppo a lungo.", Simulation: Task01Updates },
    { id: "02-account", title: "Account e privilegi", goal: "Usare i diritti amministrativi soltanto quando servono", brief: "Un amministratore può installare programmi e cambiare impostazioni che influenzano tutto il PC. Se ogni attività viene eseguita con questi diritti, anche un errore o un programma dannoso può ottenere più controllo.", details: "Un account standard permette di lavorare, navigare e aprire documenti senza poter modificare liberamente le parti più delicate del sistema. Quando serve davvero, Windows può chiedere credenziali o una conferma per elevare una singola operazione.\n\nAccount separati evitano anche di condividere password e rendono più chiaro chi ha svolto un'attività. Il principio del minimo privilegio non blocca il lavoro: assegna a ogni persona e programma soltanto i poteri necessari.\n\nDistinguerai attività quotidiane, modifiche amministrative e richieste che meritano cautela.", hint: "Se l'azione riguarda soltanto documenti, posta o web, i privilegi amministrativi quasi certamente non servono.", explanation: "Hai separato l'uso normale dalle modifiche amministrative e ridotto il rischio legato a credenziali condivise.", Simulation: Task02Accounts },
    { id: "03-uac", title: "Capire le richieste UAC", goal: "Valutare prima di consentire una modifica", brief: "Il Controllo dell'account utente, chiamato UAC, compare quando un programma vuole eseguire un'azione con privilegi elevati. La finestra non garantisce che il programma sia sicuro: ti offre un momento per decidere.", details: "Prima di approvare, confronta la richiesta con ciò che hai appena fatto. Se hai avviato intenzionalmente un programma aziendale verificato per una modifica concordata, la richiesta è coerente. Se compare senza motivo o mostra un autore sconosciuto, fermarsi è la scelta più prudente.\n\nAnche il nome di un programma può essere copiato. Editore, origine del file e contesto dell'azione sono indizi da leggere insieme. Disattivare UAC elimina questo utile punto di controllo.\n\nEsaminerai tre finestre simulate e deciderai se consentire o annullare.", hint: "Chiediti: ho avviato io questa operazione, conosco il programma e la modifica è necessaria?", explanation: "Sai leggere una richiesta UAC come una decisione di sicurezza, non come un ostacolo da chiudere automaticamente.", Simulation: Task03Uac },
    { id: "04-defender", title: "Microsoft Defender", goal: "Mantenere attive le protezioni essenziali", brief: "Microsoft Defender controlla file, download e comportamenti sospetti. È già integrato in Windows e riceve aggiornamenti frequenti sulle minacce conosciute.", details: "La protezione in tempo reale osserva ciò che viene aperto o eseguito; quella cloud accelera il riconoscimento di minacce recenti. L'invio di campioni può aiutare l'analisi, mentre le esclusioni dicono all'antivirus di ignorare determinati percorsi.\n\nUn'esclusione molto ampia, come l'intera cartella Download, crea una zona non controllata proprio dove arrivano molti file esterni. Le esclusioni vanno limitate, documentate e rimosse quando non servono più.\n\nCorreggerai un pannello di protezione configurato in modo debole.", hint: "Attiva le difese principali ed elimina l'esclusione che copre troppi file.", explanation: "Hai ripristinato le protezioni principali senza creare una zona cieca nella cartella dei download.", Simulation: Task04Defender },
    { id: "05-firewall", title: "Firewall e profili di rete", goal: "Applicare regole adatte al luogo e al servizio", brief: "Il firewall decide quali comunicazioni possono raggiungere il PC. Windows usa profili diversi perché una rete domestica controllata non presenta lo stesso rischio del Wi-Fi di un aeroporto.", details: "Il profilo pubblico limita maggiormente la visibilità e le connessioni in ingresso. Il profilo privato è adatto soltanto a reti considerate affidabili. Una regola può essere ristretta a un'applicazione, una porta, una direzione e uno specifico profilo.\n\nQuando qualcosa non funziona, spegnere completamente il firewall risolve il sintomo ma rimuove molte altre difese. È preferibile identificare la comunicazione necessaria e creare un'eccezione precisa.\n\nSceglierai profili e regole per quattro casi comuni.", hint: "Su reti sconosciute scegli il profilo pubblico; per le eccezioni limita app, rete e scopo.", explanation: "Sai mantenere il firewall attivo e consentire soltanto le comunicazioni motivate dal contesto.", Simulation: Task05Firewall },
    { id: "06-permessi", title: "Condivisioni e permessi NTFS", goal: "Concedere accesso ai file senza esporli inutilmente", brief: "I permessi NTFS stabiliscono chi può leggere, modificare o amministrare file e cartelle. Dare Controllo completo a tutti è semplice, ma permette anche di cancellare dati o cambiare i permessi.", details: "Lettura consente di consultare i documenti; Modifica permette anche di crearli, cambiarli ed eliminarli. Controllo completo aggiunge la possibilità di gestire proprietà e autorizzazioni, quindi dovrebbe restare limitato agli amministratori appropriati.\n\nI gruppi rendono più semplice assegnare lo stesso accesso a persone con lo stesso ruolo. I dati sensibili, come le paghe, devono essere separati dai documenti comuni e disponibili soltanto a chi ne ha bisogno.\n\nAssegnerai quattro permessi tenendo conto dello scopo di ogni cartella.", hint: "Concedi il livello minimo che permette al gruppo di svolgere il proprio lavoro.", explanation: "Hai distinto consultazione, lavoro sui file e gestione dei permessi proteggendo i dati riservati.", Simulation: Task06Permissions },
    { id: "07-avvio", title: "Programmi all'avvio", goal: "Ridurre gli elementi automatici non necessari", brief: "Alcuni programmi partono insieme a Windows per offrire notifiche o servizi immediati. Troppi elementi rallentano l'accesso e un programma sconosciuto all'avvio merita una verifica.", details: "Gestione attività mostra nome, editore, stato e impatto di avvio. L'impatto alto descrive il consumo di risorse, non la pericolosità: una videoconferenza legittima può essere pesante, mentre un programma dannoso può consumare poco.\n\nBisogna valutare se il programma è necessario fin dall'accesso, se l'editore è riconoscibile e se l'installazione era attesa. Disattivare un elemento dall'avvio non equivale a disinstallarlo e permette di riattivarlo.\n\nDeciderai quali elementi conservare e quali impedire di avviare automaticamente.", hint: "Non disattivare le notifiche di sicurezza o la VPN necessaria; valuta utilità ed editore insieme all'impatto.", explanation: "Hai alleggerito l'avvio mantenendo le funzioni di sicurezza e collegamento realmente necessarie.", Simulation: Task07Startup },
    { id: "08-eventi", title: "Visualizzatore eventi", goal: "Riconoscere tentativi di accesso anomali", brief: "Windows registra molte attività nei registri eventi. Nel registro Sicurezza, alcuni identificativi aiutano a trovare accessi riusciti, tentativi falliti e disconnessioni.", details: "L'evento 4625 indica un accesso non riuscito. Un solo evento può essere una password digitata male; molti eventi in pochi secondi, dallo stesso indirizzo e contro account diversi, assomigliano invece a un tentativo automatizzato.\n\nL'identificativo è soltanto il punto di partenza. Orario, account, origine e frequenza forniscono il contesto necessario. Non ogni errore è un attacco e non ogni accesso riuscito è legittimo.\n\nSelezionerai la sequenza che merita un approfondimento.", hint: "Cerca eventi 4625 ravvicinati e confronta indirizzo e nomi degli account.", explanation: "Hai distinto un normale utilizzo da una sequenza compatibile con tentativi ripetuti di accesso.", Simulation: Task08Events },
    { id: "09-controllo", title: "Controllo guidato del PC", goal: "Eseguire quattro verifiche di base", brief: "Una breve checklist rende visibili configurazioni che altrimenti si dimenticano: stato dell'antivirus, profili firewall, aggiornamenti installati e persone con diritti amministrativi.", details: "PowerShell offre comandi leggibili per interrogare Windows. Get-MpComputerStatus mostra lo stato di Defender; Get-NetFirewallProfile riepiloga i profili; Get-HotFix elenca correzioni installate; Get-LocalGroupMember mostra i membri di un gruppo locale.\n\nQuesti comandi osservano lo stato senza correggerlo automaticamente. Il risultato va confrontato con ciò che ci si aspetta dal PC: un amministratore sconosciuto o una protezione disattivata richiedono verifica.\n\nUserai un terminale simulato per completare i quattro controlli e leggere le risposte.", hint: "Digita help nel terminale per visualizzare i quattro comandi ammessi.", explanation: "Hai completato una checklist iniziale che unisce difese attive, aggiornamenti e privilegi locali.", Simulation: Task09Audit },
    { id: "10-quiz", title: "Quiz finale — 10 domande", goal: "Consolidare le basi di sicurezza Windows", brief: "Il quiz riprende le decisioni incontrate nello scenario: aggiornamenti, account, UAC, Defender, firewall, permessi, avvio, eventi e controlli locali.", details: "Le domande descrivono situazioni semplici e non richiedono nozioni avanzate. Cerca la risposta che riduce il rischio senza rendere inutilizzabile il PC: protezioni attive, privilegi limitati, eccezioni precise e segnali osservati nel loro contesto.\n\nPer completare il percorso servono almeno sette risposte corrette su dieci. Se non raggiungi il punteggio puoi leggere le correzioni e riprovare senza perdere i progressi precedenti.\n\nRagiona sui principi appresi invece di affidarti soltanto alla memoria.", hint: "Fonte ufficiale, minimo privilegio, difese attive e controlli regolari sono i punti di riferimento.", explanation: "Hai completato le basi della sicurezza dei sistemi Windows e possiedi una routine iniziale concreta.", Simulation: Task10Quiz },
  ],
};
