import type { Slide } from "../types";

export const traversalSlides: Slide[] = [
  {
    kicker: "Scenario 02 · Panoramica",
    title: "Directory Traversal",
    body: "Directory Traversal (o Path Traversal) è la capacità di far leggere al server un file fuori dalla cartella prevista, risalendo l'albero delle directory con i simboli ../. Nessun exploit complesso: è il sistema operativo stesso che interpreta «..» come «torna indietro di un livello».",
    note: "È la vulnerabilità con cui si passa da «vedere una pagina» a «leggere qualunque file che il processo web può aprire»: /etc/passwd, chiavi SSH, file di configurazione con password del database.",
    bullets: [
      "Un input manipolato basta: file=../",
      "Cambi marker classici: /etc/passwd su Linux, win.ini su Windows",
      "Il jackpot: credenziali in file di configurazione",
    ],
    accent: "gold",
    icon: "FolderOpen",
  },
  {
    kicker: "Task 01 · Osserva",
    title: "Come il server trova un file",
    body: "Un server ha sempre una cartella di base e ci concatena il nome che riceve: /var/www/html/pages + note.txt → /var/www/html/pages/note.txt. Il primo passo è osservare questo meccanismo dall'interno, aprendo due file legittimi e guardando come si compone il percorso finale.",
    note: "Nessun attacco qui: capire il pattern «base + input» è essenziale, perché la vulnerabilità nasce esattamente quando l'input può alterare la parte «cartella» del percorso, non solo il nome del file.",
    bullets: [
      "Esempio tipico: /read?file=note.txt",
      "Il server apre quel percorso e restituisce il contenuto",
      "Pattern diffusissimo: download di allegati, viewer di documenti",
    ],
    icon: "Eye",
  },
  {
    kicker: "Task 02 · Il primo traversal",
    title: "Salire di cartella con ../",
    body: "Nel filesystem «..» significa «la cartella genitore»: è un meccanismo standard di ogni sistema operativo. Se passi ../index.html, il resolver torna indietro di un livello e il percorso finale diventa /var/www/html/index.html — sei uscito dalla cartella prevista.",
    note: "Il difetto è che il server non si chiede mai «il percorso finale resta davvero dentro la mia base?». Il difetto più comune nei bug trovati in produzione è proprio questa verifica mancante.",
    accent: "danger",
    icon: "CornerLeftUp",
  },
  {
    kicker: "Task 03 · Uscire fino alla radice",
    title: "Leggere /etc/passwd",
    body: "Da /var/www/html/pages servono quattro ../ per arrivare a /, poi puoi navigare ovunque. Puoi anche esagerare con gli ../: risalire oltre la radice non produce errore, la radice è il limite. /etc/passwd elenca utenti, uid e home directory — è il marker classico che prova il traversal.",
    note: "/etc/passwd non contiene password (quelle in /etc/shadow, solo root), ma è la prova che il server legge file arbitrari: nel pentest è la conferma che il perimetro applicativo è saltato.",
    bullets: [
      "Payload: ?file=../../../../etc/passwd",
      "Ogni ../ risale di un livello; la radice ferma tutto",
      "Marker di sistema = prova che il traversal funziona",
    ],
    accent: "danger",
    icon: "FileKey",
  },
  {
    kicker: "Task 04 · Windows/IIS",
    title: "Backslash, drive letter, win.ini",
    body: "Su Windows la logica è identica ma cambiano i dettagli: i separatori sono \\ (anche se / funziona), i percorsi partono da C:\\, e IIS serve i file da C:\\inetpub\\wwwroot. I target di riferimento diventano win.ini (equivalente storico di /etc/passwd) e la mappa di rete in hosts.",
    note: "Il traversal è indipendente dal sistema operativo: cambia il principio di nulla, cambiano solo file di riferimento e separatori. È anche il contesto in cui vive lo scenario successivo del modulo Reverse Shell.",
    bullets: [
      "Target tipico: C:\\Windows\\win.ini",
      "C:\\Windows\\System32\\drivers\\etc\\hosts",
      "Stesso attacco, dettagli diversi",
    ],
    icon: "HardDrive",
  },
  {
    kicker: "Task 05 · Primo bypass",
    title: "URL-encoding: %2e%2e%2f",
    body: "La difesa ingenua è: «se nella stringa ci sono due punti attaccati, blocco». Funziona per cinque minuti: chiunque componga la richiesta può codificare i caratteri — %2e è ., %2f è /. Il filtro non vede più «..», ma il decoder che sta dietro sì.",
    note: "La regola generale è una sola: non validare mai una stringa nella sua forma di superficie. Prima canonicalizza (decodifica, normalizza), poi decidi se accettarla. Chi decodifica per ultimo vince.",
    bullets: [
      "%2e = . · %2f = /",
      "Filtro e decoder erano in ordine sbagliato",
      "Canonicalizza prima di validare",
    ],
    accent: "danger",
    icon: "Repeat",
  },
  {
    kicker: "Task 06 · Due decoder in cascata",
    title: "Doppia codifica con %25",
    body: "Molte applicazioni attraversano più componenti — reverse proxy, framework, application server — e ognuno tende a decodificare l'URL. Se lo sviluppatore mette il filtro nel mezzo, puoi codificare due volte il payload: %252e diventa %2e dopo il primo giro, e . dopo il secondo.",
    note: "Morale: canonicalizzazione una volta sola, in un solo posto, poi controlla. Ogni decoder aggiunto è una nuova occasione per sbagliare — la difesa non è regex, è confinare il percorso assoluto.",
    bullets: [
      "%25 = % · quindi %252e → %2e → .",
      "Il filtro vedeva una stringa pulita, il filesystem riceveva i ../ veri",
      "Confronta il percorso assoluto con la cartella consentita",
    ],
    accent: "danger",
    icon: "Shuffle",
  },
  {
    kicker: "Task 07 · Un layer aggiunge, un altro tronca",
    title: "Il trucco storico del null byte",
    body: "Un'altra difesa comune: «servo solo file .txt, se non finisce con .txt lo aggiungo io». Nei runtime del passato (PHP 5, ColdFusion, Perl) le API filesystem erano scritte in C e trattavano \\0 come fine stringa: il server vedeva «passwd\\0.txt» e passava alla lettura «passwd».",
    note: "I runtime moderni bloccano i null byte, quindi il trucco specifico non funziona più quasi mai. Ma il pattern — due layer che interpretano la stessa stringa in modo diverso — si ripresenta continuamente in forme nuove.",
    icon: "Scissors",
  },
  {
    kicker: "Task 08-09 · Il vero obiettivo",
    title: "Segreti nei file di configurazione",
    body: "Un attaccante non si accontenta di /etc/passwd: il vero jackpot sono app.conf, .env, database.yml, web.config — spesso con credenziali del DB e chiavi API in chiaro. E il traversal non abita solo negli URL: anche un body JSON con un campo filename se finisce in una chiamata al filesystem è a rischio.",
    note: "Con host, utente e password del DB, l'attaccante si collega direttamente al database bypassando tutta la logica applicativa. Difesa a livello di design: identificatori opachi (id nel DB → path lato server) e segreti fuori dai file — variabili d'ambiente o secret manager.",
    bullets: [
      "app.conf / .env / database.yml: credenziali in chiaro",
      "Body JSON, header, cookie: tutto input manipolabile",
      "id opachi + secret manager = classe di bug eliminata",
    ],
    accent: "danger",
    icon: "Vault",
  },
  {
    kicker: "Task 10 · Sintesi",
    title: "Le tre regole d'oro",
    body: "Dieci domande finali per fissare i concetti, poi si passa alla pratica. Le domande ripercorrono il modulo: cos'è il traversal, come si aggirano i filtri, dove si nasconde oltre che negli URL, e le difese davvero efficaci. Se sbagli, torna al task corrispondente — non c'è penalità nel riprovare.",
    note: "Consiglio: rispondi prima senza rileggere le slide, poi pensa a dove sta il decoder, dove sta il filtro e se il segreto abita dentro un file leggibile dal processo web.",
    bullets: [
      "1 · Canonicalizza prima di validare: decodifica e normalizza, poi controlla",
      "2 · Confina il processo: chroot, container, permessi minimi sul filesystem",
      "3 · Mai passare nomi di file dal client: usa identificatori opachi nel DB",
    ],
    accent: "success",
    icon: "ShieldCheck",
  },
];
