import { useState } from "react";
import { ArrowDown, ArrowUp, Footprints } from "lucide-react";
import { Button } from "@/components/ui/button";
import { InfoNote, SuccessNote } from "@/components/lab/Feedback";
import type { TaskContext } from "../../types";
import { cn } from "@/lib/utils";
const CORRECT=[
 {id:"login",time:"08:02",event:"ConsoleLogin",detail:"Accesso di admin-backup da un nuovo indirizzo"},
 {id:"policy",time:"08:04",event:"PutUserPolicy",detail:"Aggiunto AdministratorAccess all'utente"},
 {id:"trail",time:"08:06",event:"StopLogging",detail:"Interrotta la registrazione del trail principale"},
 {id:"bucket",time:"08:08",event:"PutBucketPolicy",detail:"Bucket documenti reso accessibile pubblicamente"},
] as const;
const START = [CORRECT[2], CORRECT[0], CORRECT[3], CORRECT[1]];
export default function Task08Trail({markComplete,isComplete}:TaskContext){const [items,setItems]=useState([...START]);const [checked,setChecked]=useState(false);const move=(i:number,d:number)=>{const j=i+d;if(j<0||j>=items.length)return;const current=items[i];const destination=items[j];if(!current||!destination)return;const n=[...items];n[i]=destination;n[j]=current;setItems(n);setChecked(false)};const good=items.every((x,i)=>x.id===CORRECT[i]?.id);return <div><div className="rounded-lg border border-border bg-surface p-5"><div className="mb-4 flex items-center gap-3"><Footprints className="text-accent"/><p className="font-semibold">CloudTrail · Ricostruzione incidente</p></div><div className="relative space-y-3 before:absolute before:bottom-5 before:left-[18px] before:top-5 before:w-px before:bg-border">{items.map((item,i)=><div key={item.id} className={cn("relative grid grid-cols-[38px_minmax(0,1fr)_auto] gap-3 rounded-lg border bg-background p-3",checked&&(good?"border-success/50":"border-destructive/40"))}><span className="z-10 grid h-9 w-9 place-items-center rounded-full border border-accent bg-surface font-mono text-xs text-accent">{i+1}</span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><strong className="font-mono text-xs text-accent">{item.event}</strong><span className="text-xs text-muted-foreground">{item.time}</span></div><p className="mt-1 text-sm leading-relaxed">{item.detail}</p></div><div className="flex flex-col"><Button size="icon" variant="ghost" disabled={i===0} onClick={()=>move(i,-1)} aria-label="Sposta evento prima"><ArrowUp/></Button><Button size="icon" variant="ghost" disabled={i===items.length-1} onClick={()=>move(i,1)} aria-label="Sposta evento dopo"><ArrowDown/></Button></div></div>)}</div><Button className="mt-4" onClick={()=>{setChecked(true);if(good)markComplete();}}>Ricostruisci la sequenza</Button>{checked&&!good&&<p className="mt-3 text-sm text-destructive">Parti dall'accesso iniziale, poi segui l'aumento dei privilegi e i tentativi di nascondere o ampliare l'azione.</p>}</div>{isComplete?<SuccessNote>Hai ricostruito una catena credibile: accesso, aumento dei privilegi, disattivazione dei log ed esposizione dei dati.</SuccessNote>:<InfoNote>CloudTrail registra chiamate e modifiche nell'account. Ordinare gli eventi aiuta a capire causa, impatto e risposta necessaria.</InfoNote>}</div>}
