import { useState } from "react";
import { ArrowDown, ArrowUp, Network } from "lucide-react";
import { Button } from "@/components/ui/button";
import { InfoNote, SuccessNote } from "@/components/lab/Feedback";
import type { TaskContext } from "../../types";
import { cn } from "@/lib/utils";
const TARGET=[
 {id:"web",layer:"Load balancer pubblico",port:"HTTPS 443",source:"Internet"},
 {id:"app",layer:"Server applicativo",port:"App 8080",source:"Solo dal load balancer"},
 {id:"db",layer:"Database",port:"PostgreSQL 5432",source:"Solo dal server applicativo"},
];
const INITIAL=[TARGET[2],TARGET[0],TARGET[1]];
export default function Task06Groups({markComplete,isComplete}:TaskContext){const [rules,setRules]=useState(INITIAL);const [checked,setChecked]=useState(false);const move=(i:number,d:number)=>{const j=i+d;if(j<0||j>=rules.length)return;const n=[...rules];[n[i],n[j]]=[n[j]!,n[i]!];setRules(n);setChecked(false)};const good=rules.every((r,i)=>r.id===TARGET[i]?.id);return <div><div className="rounded-lg border border-border bg-surface p-5"><div className="mb-4 flex items-center gap-3"><Network className="text-accent"/><div><p className="font-semibold">Percorso consentito</p><p className="text-xs text-muted-foreground">Internet → sito → applicazione → dati</p></div></div><ol className="space-y-3">{rules.map((r,i)=><li key={r.id} className={cn("grid grid-cols-[36px_minmax(0,1fr)_auto] items-center gap-3 rounded-lg border p-3",checked&&(good?"border-success/50":"border-destructive/50"))}><span className="grid h-9 w-9 place-items-center rounded-md bg-accent/10 font-mono text-accent">{i+1}</span><div className="min-w-0"><p className="text-sm font-semibold">{r.layer}</p><p className="break-words font-mono text-xs text-muted-foreground">{r.port} · Origine: {r.source}</p></div><div className="flex flex-col gap-1"><Button size="icon" variant="ghost" disabled={i===0} onClick={()=>move(i,-1)} aria-label="Sposta regola in alto"><ArrowUp/></Button><Button size="icon" variant="ghost" disabled={i===rules.length-1} onClick={()=>move(i,1)} aria-label="Sposta regola in basso"><ArrowDown/></Button></div></li>)}</ol><Button className="mt-4" onClick={()=>{setChecked(true);if(good)markComplete();}}>Prova il percorso</Button>{checked&&!good&&<p className="mt-3 text-sm text-destructive">Il database o l'applicazione sono esposti prima del livello che dovrebbe proteggerli.</p>}</div>{isComplete?<SuccessNote>Solo il load balancer riceve traffico da Internet. Gli altri livelli si fidano di un Security Group preciso, non di tutto il mondo.</SuccessNote>:<InfoNote>Una regola 0.0.0.0/0 significa “da qualunque indirizzo”. È appropriata per il sito pubblico, non per database e porte amministrative.</InfoNote>}</div>}
