import type { Slide } from "../types";

export const revengSlides: Slide[] = [
  {
    kicker: "Scenario 04 · Panoramica",
    title: "Reverse Engineering (base)",
    body: "Il reverse engineering è l'arte di capire cosa fa un programma leggendolo, senza eseguirlo. In questo scenario trovi un update.ps1 apparentemente innocuo sul PC di un utente e lo smontiamo pezzo per pezzo: prima lo leggiamo, poi decodifichiamo quello che nasconde, infine scriviamo lo script che cancella i suoi effetti.",
    note: "Non è magia nera: è metodo. Tutti i programmi malevoli fatti in fretta usano gli stessi pochi trucchi di offuscamento — e noi li vedremo tutti, uno alla volta.",
    bullets: [
      "Leggere un codice è il primo passo per difendersi",
      "Tre livelli di offuscamento, ognuno più tosto del precedente",
      "L'AI può aiutarti: devi solo fargli le domande giuste",
    ],
    accent: "gold",
    icon: "Wrench",
  },
  {
    kicker: "Task 01 · Le basi",
    title: "Com'è fatto uno script PowerShell",
    body: "Prima di smontare un problema di reverse, bisogna saper leggere il linguaggio. PowerShell è il linguaggio nativo di amministrazione di Windows: ogni comando ha la forma Verbo-Nome (Get-Date, Write-Host, Set-ItemProperty), le variabili iniziano con $, i commenti con #.",
    note: "Sono le tre cose che ti servono per non essere in balia dello script sospetto del prossimo task. Guarda lo script PowerShell più innocuo possibile: «ciao mondo con la data di oggi».",
    bullets: [
      "Comandi = Verbo-Nome: Get-Date, Write-Host",
      "Variabili = $nome",
      "Commenti = # riga di spiegazione",
    ],
    icon: "BookOpen",
  },
  {
    kicker: "Task 02 · Triage",
    title: "Il primo colpo d'occhio: chi lo chiama e come",
    body: "Arriva lo script sospetto: update.ps1, un launcher che sembra scaricare un aggiornamento. Il primo passo del reverse è il triage: senza eseguire nulla, cerchiamo le parole chiave che tradiscono le cattive intenzioni — -EncodedCommand, download, esecuzione nascosta, persistenza.",
    note: "Il launcher mostra, solo a scopo didattico, una persistenza simulata nel registro di Windows (chiave Run), il download di %TEMP%\\a.ps1 e l'esecuzione. Mai eseguito davvero.",
    bullets: [
      "-EncodedCommand: codice nascosto in Base64",
      "Chiave Run del registro = si avvia a ogni accensione",
      "Download da IP sospetto + esecuzione = allarme",
    ],
    accent: "danger",
    icon: "AlertTriangle",
  },
  {
    kicker: "Task 03 · Primo livello",
    title: "Decodificare Base64",
    body: "-EncodedCommand riceve il comando codificato in Base64 con testo UTF-16LE. Nel task decodifichiamo davvero la stringa nel browser e scopriamo cosa lo script fa in realtà: dietro quella fila di lettere senza senso c'era un semplice comando PowerShell.",
    note: "Base64 non è crittografia: è solo una codifica, chiunque la può leggere. Esempio: PowerShell -EncodedCommand <base64> → decodifica → il comando reale, chiaro e leggibile.",
    bullets: [
      "Base64 = maschera, non segreto",
      "UTF-16LE: due byte per ogni carattere",
      "Decodifica senza eseguire: leggere è sicuro",
    ],
    accent: "danger",
    icon: "FileKey",
  },
  {
    kicker: "Task 04-05 · Offuscamento, round 2",
    title: "Codice smontato e rimontato",
    body: "Il malware non basta nascondersi in Base64: smonta le stringhe in pezzi e le rimonta a runtime. Nel task 4 ricostruiamo un Invoke-Expression nascosto nella concatenazione; nel task 5 decodifichiamo un array di codici numerici che rappresentano caratteri.",
    note: "Sono due varianti dello stesso trucco: «scrivere le cose in un modo in cui non si capisce al volo, ma che il computer ricostruisce da solo». Esempio: [char[]](72,73) → 'HI'.",
    bullets: [
      "Concatenazione: stringhe spezzate e ricomposte",
      "Char-code: ogni lettera diventa un numero",
      "Lo schema si ripete: ricostruisci → leggi → capisci",
    ],
    accent: "danger",
    icon: "Puzzle",
  },
  {
    kicker: "Task 06 · Offuscamento, round 3",
    title: "XOR: ogni carattere mescolato con una chiave",
    body: "Terzo e ultimo livello: XOR. Ogni carattere del messaggio viene «mescolato» con un valore segreto (la chiave). Con lo stesso valore, l'operazione si annulla: applichi XOR con la chiave al messaggio cifrato e torna in chiaro. Nel task la trovi muovendo uno slider da 1 a 255.",
    note: "XOR con una chiave singola è indecifrabile in teoria ma debole in pratica: prova tutte le 256 chiavi possibili e una è quella giusta — esattamente quello che farai con lo slider.",
    bullets: [
      "XOR è reversibile: stesso valore per cifrare e decifrare",
      "Chiave a 1 byte = 256 possibilità, tutte provabili",
      "Lo slider ti fa vedere la chiave giusta in tempo reale",
    ],
    accent: "danger",
    icon: "KeyRound",
  },
  {
    kicker: "Task 07 · L'aiuto dell'AI",
    title: "Farsi aiutare dall'AI con i prompt giusti",
    body: "Ora che conosci lo script, proviamo a farci aiutare dall'AI. La differenza tra un risultato utile e uno generico sta tutta nel prompt: dal contesto (che tipo di file, dove l'hai trovato) alla richiesta precisa (che cosa vuoi sapere, in che formato).",
    note: "Regola d'oro: non chiedere «dimmi se questo è pericoloso» — chiedi «spiega passo per passo cosa fa questo script, elenca gli indicatori di compromissione e scrivi lo script che annulla i suoi effetti».",
    bullets: [
      "Contesto: tipo di file, dove l'hai trovato",
      "Domande precise, risposta precisa",
      "Chiedi output strutturato: comportamento, IOC, remediation",
    ],
    icon: "Bot",
  },
  {
    kicker: "Task 08 · Verifica",
    title: "Classificare il comportamento reale",
    body: "L'AI ti ha dato un'analisi, ma non va presa per buona: un analista verifica. Nel task classifichi tu il comportamento reale dello script — persistenza nel registro, download, esecuzione remota — scegliendo le categorie giuste tra quelle proposte.",
    note: "Mai fidarsi ciecamente di un'analisi automatica: è il punto di partenza, non la conclusione. La verifica umana è parte del lavoro.",
    accent: "danger",
    icon: "ClipboardCheck",
  },
  {
    kicker: "Task 09 · Controcolpo",
    title: "Scrivere lo script che annulla il malware",
    body: "Qui si chiude il cerchio: dal capire al riparare. Scrivi lo script inverso che rimuove la chiave di persistenza dal registro, elimina i file scaricati e lascia il sistema pulito come prima. Ogni riga corrisponde a un danno che abbiamo visto prima.",
    note: "Esempio: se il malware ha scritto in HKCU:\\Software\\...\\Run\\OneDriveSync, la remediation usa Remove-ItemProperty sulla stessa chiave e rimuove i file temporanei scaricati.",
    bullets: [
      "Ogni danno → una riga di pulizia",
      "Registro, file temporanei, processo: in quest'ordine",
      "Testa su ambiente isolato, mai sulla macchina reale",
    ],
    accent: "success",
    icon: "Undo2",
  },
  {
    kicker: "Task 10 · Sintesi",
    title: "Quiz finale: il metodo nel suo insieme",
    body: "Dieci domande per fissare l'intero metodo: leggere PowerShell, riconoscere i tre livelli di offuscamento, usare bene l'AI e scrivere la remediation. Se sbagli, torna al task corrispondente — non c'è penalità nel riprovare.",
    note: "Consiglio: rispondi prima senza rileggere le slide. Il reverse engineering è esattamente questo ciclo — osserva, decodifica, verifica, ripara — ripetuto ogni volta con un campione diverso.",
    bullets: [
      "1 · Leggi, non eseguire: il reverse parte sempre da qui",
      "2 · Offuscamento = trucco prevedibile, sempre reversibile",
      "3 · L'AI accelera, ma la verifica resta tuo compito",
    ],
    accent: "success",
    icon: "ShieldCheck",
  },
];
