/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModulesSlugRouteImport } from './routes/modules.$slug'
import { Route as ModulesSlugIndexRouteImport } from './routes/modules.$slug.index'
import { Route as ModulesSlugTaskIdRouteImport } from './routes/modules.$slug.$taskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesSlugRoute = ModulesSlugRouteImport.update({
  id: '/modules/$slug',
  path: '/modules/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesSlugIndexRoute = ModulesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModulesSlugRoute,
} as any)
const ModulesSlugTaskIdRoute = ModulesSlugTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => ModulesSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/modules/$slug': typeof ModulesSlugRouteWithChildren
  '/modules/$slug/$taskId': typeof ModulesSlugTaskIdRoute
  '/modules/$slug/': typeof ModulesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/modules/$slug/$taskId': typeof ModulesSlugTaskIdRoute
  '/modules/$slug': typeof ModulesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/modules/$slug': typeof ModulesSlugRouteWithChildren
  '/modules/$slug/$taskId': typeof ModulesSlugTaskIdRoute
  '/modules/$slug/': typeof ModulesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/modules/$slug' | '/modules/$slug/$taskId' | '/modules/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/modules/$slug/$taskId' | '/modules/$slug'
  id:
    | '__root__'
    | '/'
    | '/modules/$slug'
    | '/modules/$slug/$taskId'
    | '/modules/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModulesSlugRoute: typeof ModulesSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$slug': {
      id: '/modules/$slug'
      path: '/modules/$slug'
      fullPath: '/modules/$slug'
      preLoaderRoute: typeof ModulesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$slug/': {
      id: '/modules/$slug/'
      path: '/'
      fullPath: '/modules/$slug/'
      preLoaderRoute: typeof ModulesSlugIndexRouteImport
      parentRoute: typeof ModulesSlugRoute
    }
    '/modules/$slug/$taskId': {
      id: '/modules/$slug/$taskId'
      path: '/$taskId'
      fullPath: '/modules/$slug/$taskId'
      preLoaderRoute: typeof ModulesSlugTaskIdRouteImport
      parentRoute: typeof ModulesSlugRoute
    }
  }
}

interface ModulesSlugRouteChildren {
  ModulesSlugTaskIdRoute: typeof ModulesSlugTaskIdRoute
  ModulesSlugIndexRoute: typeof ModulesSlugIndexRoute
}

const ModulesSlugRouteChildren: ModulesSlugRouteChildren = {
  ModulesSlugTaskIdRoute: ModulesSlugTaskIdRoute,
  ModulesSlugIndexRoute: ModulesSlugIndexRoute,
}

const ModulesSlugRouteWithChildren = ModulesSlugRoute._addFileChildren(
  ModulesSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModulesSlugRoute: ModulesSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
