import { useEffect, useState } from "react";
import { InteractiveTerminal, type TermResponse } from "@/components/lab/InteractiveTerminal";
import { InfoNote, SuccessNote } from "@/components/lab/Feedback";
import { cn } from "@/lib/utils";
import type { TaskContext } from "../../types";
const CHECKS=[
 {key:"defender",label:"Stato antivirus",command:"Get-MpComputerStatus"},
 {key:"firewall",label:"Profili firewall",command:"Get-NetFirewallProfile"},
 {key:"updates",label:"Aggiornamenti recenti",command:"Get-HotFix"},
 {key:"admins",label:"Amministratori locali",command:"Get-LocalGroupMember Administrators"},
];
export default function Task09Audit({markComplete,isComplete}:TaskContext){const [done,setDone]=useState<string[]>([]);useEffect(()=>{if(done.length===CHECKS.length&&!isComplete)markComplete();},[done,isComplete,markComplete]);const record=(key:string)=>setDone((previous)=>previous.includes(key)?previous:[...previous,key]);const handle=(raw:string):TermResponse|TermResponse[]=>{const command=raw.trim().toLowerCase();if(command==="help"||command==="?")return CHECKS.map((check)=>({text:check.command,kind:"info" as const}));if(command==="get-mpcomputerstatus"){record("defender");return [{text:"AntivirusEnabled        : True",kind:"info"},{text:"RealTimeProtectionEnabled: True"}];}if(command==="get-netfirewallprofile"){record("firewall");return [{text:"Domain  Enabled: True"},{text:"Private Enabled: True"},{text:"Public  Enabled: True"}];}if(command==="get-hotfix"){record("updates");return [{text:"HotFixID    InstalledOn"},{text:"KB5070211   09/09/2026",kind:"info"}];}if(command==="get-localgroupmember administrators"){record("admins");return [{text:"Name                 ObjectClass"},{text:"WORKSTATION\\Admin   User",kind:"info"}];}return {text:"Comando non previsto. Digita help per vedere i quattro controlli.",kind:"err"};};return <div className="grid min-w-0 gap-4 md:grid-cols-[minmax(0,1fr)_260px]"><InteractiveTerminal title="PowerShell — controllo locale" prompt="PS C:\\> " heightClass="min-h-[310px]" onCommand={handle}/><aside className="min-w-0 rounded-lg border border-border bg-surface p-4"><h3 className="mb-3 font-mono text-xs uppercase text-accent">Checklist Windows</h3><ul className="space-y-3">{CHECKS.map((check)=><li key={check.key} className={cn("flex min-w-0 gap-2 text-sm",done.includes(check.key)?"text-foreground":"text-muted-foreground")}><span className={cn("mt-1.5 h-2 w-2 shrink-0 rounded-full",done.includes(check.key)?"bg-success":"bg-border")}/><span className="min-w-0">{check.label}<code className="mt-1 block break-all text-[10px] text-muted-foreground">{check.command}</code></span></li>)}</ul></aside><div className="md:col-span-2">{isComplete?<SuccessNote>Hai osservato quattro aree diverse: antivirus, firewall, patch e membri del gruppo amministratori. Insieme offrono una prima fotografia del PC.</SuccessNote>:<InfoNote>Digita help per vedere i comandi disponibili. La checklist non modifica il sistema: raccoglie informazioni da confrontare con lo stato atteso.</InfoNote>}</div></div>}
