import { ShieldAlert, X } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { InfoNote, SuccessNote } from "@/components/lab/Feedback";
import { cn } from "@/lib/utils";
import type { TaskContext } from "../../types";
const PROMPTS=[
 {app:"Contoso VPN",publisher:"Contoso S.p.A. — Verificato",origin:"Scaricato dal portale aziendale",allow:true},
 {app:"Free_Cleaner_2026.exe",publisher:"Autore sconosciuto",origin:"Cartella Download — avvio inatteso",allow:false},
 {app:"Windows Terminal",publisher:"Microsoft Windows — Verificato",origin:"Avviato da te per una modifica concordata",allow:true},
];
export default function Task03Uac({markComplete,isComplete}:TaskContext){const [step,setStep]=useState(0);const [wrong,setWrong]=useState(false);const prompt=PROMPTS[step];const decide=(allow:boolean)=>{if(!prompt)return;if(allow!==prompt.allow){setWrong(true);return;}setWrong(false);if(step===PROMPTS.length-1){markComplete();return;}setStep((value)=>value+1);};return <div><div className="mx-auto max-w-xl overflow-hidden rounded-lg border border-border bg-surface shadow-lg"><div className="flex items-center gap-3 border-b border-border bg-primary/15 p-4"><ShieldAlert className="h-8 w-8 text-accent"/><div><p className="font-semibold text-foreground">Controllo dell'account utente</p><p className="text-xs text-muted-foreground">Vuoi consentire a questa app di apportare modifiche?</p></div></div>{prompt?<div className="space-y-4 p-5"><div><p className="text-lg font-semibold text-foreground">{prompt.app}</p><p className="mt-1 text-sm text-muted-foreground">Editore: {prompt.publisher}</p><p className="text-sm text-muted-foreground">Origine: {prompt.origin}</p></div><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>decide(false)}><X/>No</Button><Button onClick={()=>decide(true)}><ShieldAlert/>Sì</Button></div></div>:null}</div><div className="mt-3 flex items-center justify-between text-xs text-muted-foreground"><span>Richiesta {Math.min(step+1,PROMPTS.length)} di {PROMPTS.length}</span><span className={cn(wrong&&"text-destructive")}>{wrong?"Osserva editore, origine e motivo della richiesta.":"Non approvare per abitudine."}</span></div>{isComplete?<SuccessNote>Hai trattato UAC come un punto di decisione: hai confrontato ciò che stavi facendo con identità e provenienza del programma.</SuccessNote>:<InfoNote>UAC non dichiara automaticamente che un programma è sicuro. Ti avvisa che sta per ottenere privilegi maggiori e ti offre il tempo di controllare.</InfoNote>}</div>}
